"""add lead and message memory fields

Revision ID: c658d7e2625a
Revises: 
Create Date: 2026-09-27 01:14:46.497423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c658d7e2625a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('business_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('lead_volume', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('interested_agent', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('demo_date', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('demo_time', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('demo_datetime', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('demo_status', sa.String(), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('sender_type')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('demo_status')
        batch_op.drop_column('demo_datetime')
        batch_op.drop_column('demo_time')
        batch_op.drop_column('demo_date')
        batch_op.drop_column('interested_agent')
        batch_op.drop_column('lead_volume')
        batch_op.drop_column('business_type')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
